//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdaptivBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdaptivBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;AdaptivBot&gt;
        ///
        ///	&lt;GeneralSettings&gt;
        ///		&lt;ExcelExecutablePath&gt;&lt;/ExcelExecutablePath&gt;
        ///		&lt;QlikviewUATFolder&gt;\\10952APPJNB0001\PS.Portfolio_Sensitivities\8.Import\New&lt;/QlikviewUATFolder&gt;
        ///		&lt;QlikviewProductionFolder&gt;\\10952appprdsdc4\Portfolio Analysis\8.Import\New&lt;/QlikviewProductionFolder&gt;
        ///	&lt;/GeneralSettings&gt;
        ///
        ///	&lt;RiskViewSettings&gt;
        ///		&lt;BaseExtractionFolder&gt;\\pcibtighnas1\cbsdata\Portfolio Analysis\Data&lt;/BaseExtractionFolder&gt;
        ///		&lt;SubExtractionFolder&gt;[InstrumentBatch]&lt;/Su [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AdaptivBot {
            get {
                return ResourceManager.GetString("AdaptivBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;header&gt;
        ///    &lt;title&gt;Extraction Complete with Errors&lt;/title&gt;
        ///&lt;/header&gt;
        ///&lt;body style=&quot;background-color:#212121;&quot;&gt;
        ///    &lt;h1 style=&quot;color:white; font-family:&apos;Corbel&apos;; font-size: 32; text-align: center; line-height: 2; font-weight:100&quot;&gt;Extraction Complete with Errors&lt;/h1&gt;
        ///    &lt;img src=&quot;AdaptivBotRedCross.png&quot; style=&quot;display: block; margin-left: 41%;&quot; width=&quot;30%&quot;&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string ExtractionCompleteWithErrors {
            get {
                return ResourceManager.GetString("ExtractionCompleteWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;header&gt;
        ///    &lt;title&gt;Extraction Complete without Errors&lt;/title&gt;
        ///&lt;/header&gt;
        ///&lt;body style=&quot;background-color:#212121;&quot;&gt;
        ///    &lt;h1 style=&quot;color:white; font-family:&apos;Corbel&apos;; font-size: 32; text-align: center; line-height: 2; font-weight:100&quot;&gt;Extraction Complete without Errors&lt;/h1&gt;
        ///    &lt;img src=&quot;AdaptivBotGreenCheckMark.png&quot; style=&quot;display: block; margin-left: 41%;&quot; width=&quot;30%&quot;&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;
        ///.
        /// </summary>
        internal static string ExtractionCompleteWithoutErrors {
            get {
                return ResourceManager.GetString("ExtractionCompleteWithoutErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;header&gt;
        ///    &lt;title&gt;Extraction Complete with Warnings&lt;/title&gt;
        ///&lt;/header&gt;
        ///&lt;body style=&quot;background-color:#212121;&quot;&gt;
        ///&lt;h1 style=&quot;color:white; font-family:&apos;Corbel&apos;; font-size: 32; text-align: center; line-height: 2; font-weight:100&quot;&gt;Extraction Complete with Warnings&lt;/h1&gt;
        ///&lt;img src=&quot;AdaptivBotOrangeCheckMark.png&quot; style=&quot;display: block; margin-left: 41%;&quot; width=&quot;30%&quot;&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;
        ///.
        /// </summary>
        internal static string ExtractionCompleteWithWarnings {
            get {
                return ResourceManager.GetString("ExtractionCompleteWithWarnings", resourceCulture);
            }
        }
    }
}
